// Sample partnerships data for UCAEP website
export const samplePartnershipsData = [
  {
    name: "Food and Agriculture Organization (FAO)",
    organization: "FAO",
    partner_type: "international",
    description: "The Food and Agriculture Organization of the United Nations works with UCAEP to promote sustainable agriculture and food security in the Comoros. Our partnership focuses on capacity building, technical assistance, and policy development.",
    website: "https://www.fao.org",
    logo_url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Dr. Maria Santos",
    email: "maria.santos@fao.org",
    phone: "+39 06 57051",
    country: "Italy",
    focus_areas: ["Food Security", "Sustainable Agriculture", "Capacity Building"],
    partnership_start_date: "2020-01-15",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    name: "Ministry of Agriculture, Livestock, and Fisheries",
    organization: "Ministry of Agriculture",
    partner_type: "government",
    description: "Our primary government partner in advancing agricultural policies and programs across the Comoros. We collaborate on policy development, regulatory frameworks, and national agricultural strategies.",
    website: "https://www.agriculture.km",
    logo_url: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Hon. Ahmed Said",
    email: "ahmed.said@agriculture.km",
    phone: "+269 773 123 456",
    country: "Comoros",
    focus_areas: ["Policy Development", "Regulatory Framework", "National Strategy"],
    partnership_start_date: "2018-03-01",
    status: "active",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    name: "Comoros Development Bank",
    organization: "CDB",
    partner_type: "local",
    description: "Financial partner providing credit facilities and investment support for agricultural projects. We work together to facilitate access to finance for farmers, breeders, and fishers across the Comoros.",
    website: "https://www.cdb.km",
    logo_url: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Fatima Hassan",
    email: "fatima.hassan@cdb.km",
    phone: "+269 773 987 654",
    country: "Comoros",
    focus_areas: ["Agricultural Finance", "Investment Support", "Credit Facilities"],
    partnership_start_date: "2019-06-15",
    status: "active",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    name: "World Wildlife Fund (WWF)",
    organization: "WWF",
    partner_type: "ngo",
    description: "Environmental conservation partner focused on sustainable fishing practices and marine ecosystem protection. Our collaboration promotes responsible fishing and marine biodiversity conservation.",
    website: "https://www.wwf.org",
    logo_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Dr. Jean-Pierre Dubois",
    email: "jp.dubois@wwf.org",
    phone: "+41 22 364 9111",
    country: "Switzerland",
    focus_areas: ["Marine Conservation", "Sustainable Fishing", "Biodiversity"],
    partnership_start_date: "2021-09-01",
    status: "active",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    name: "AgriComoros Trading Company",
    organization: "AgriComoros",
    partner_type: "private",
    description: "Private sector partner specializing in agricultural exports and market development. We collaborate to improve market access for Comorian agricultural products and enhance value chains.",
    website: "https://www.agricomoros.com",
    logo_url: "https://images.unsplash.com/photo-1574263867126-3b1c4b0b0b0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Omar Ali",
    email: "omar.ali@agricomoros.com",
    phone: "+269 773 555 123",
    country: "Comoros",
    focus_areas: ["Export Development", "Market Access", "Value Chains"],
    partnership_start_date: "2020-11-20",
    status: "active",
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    name: "International Fund for Agricultural Development (IFAD)",
    organization: "IFAD",
    partner_type: "international",
    description: "International development partner providing funding and technical support for rural development projects. Our partnership focuses on improving rural livelihoods and agricultural productivity.",
    website: "https://www.ifad.org",
    logo_url: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Dr. Sarah Johnson",
    email: "sarah.johnson@ifad.org",
    phone: "+39 06 54591",
    country: "Italy",
    focus_areas: ["Rural Development", "Agricultural Productivity", "Livelihoods"],
    partnership_start_date: "2019-04-10",
    status: "active",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    name: "Comoros Farmers Cooperative Union",
    organization: "CFCU",
    partner_type: "local",
    description: "Local farmers' organization representing agricultural cooperatives across the Comoros. We work together to strengthen farmer organizations and improve collective bargaining power.",
    website: "https://www.cfcu.km",
    logo_url: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Aisha Mohamed",
    email: "aisha.mohamed@cfcu.km",
    phone: "+269 773 777 888",
    country: "Comoros",
    focus_areas: ["Farmer Organizations", "Collective Bargaining", "Cooperative Development"],
    partnership_start_date: "2018-08-15",
    status: "active",
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    name: "African Development Bank (AfDB)",
    organization: "AfDB",
    partner_type: "international",
    description: "Regional development bank providing infrastructure financing and technical assistance for agricultural development projects in the Comoros.",
    website: "https://www.afdb.org",
    logo_url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&q=80",
    contact_person: "Dr. Ibrahim Traore",
    email: "i.traore@afdb.org",
    phone: "+225 20 20 49 50",
    country: "Côte d'Ivoire",
    focus_areas: ["Infrastructure Financing", "Technical Assistance", "Regional Development"],
    partnership_start_date: "2021-01-20",
    status: "active",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export default samplePartnershipsData;
